
pageController:
  message: "Hello from a YAML file"
server:
  port: 8080
appconfig:
  app-name: "My Application"
  app-descriptiom: "Cool Application"
  admin-first-name: "Younes"
  admin-last-name: "NAJA"
  admin-email: "naja.younes@gmail.com"